# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AccesRecs' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AccesRecs
  pod 'FuzzyMatchingSwift'
  target 'AccesRecsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AccesRecsUITests' do
    # Pods for testing
  end

end
